version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: "rabbitmq:management"
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


